# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techdome-frontend-deployment
  namespace: techdome
  labels:
    app: techdome-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: techdome-frontend
  template:
    metadata:
      labels:
        app: techdome-frontend
    spec:
      containers:
      - name: techdome-frontend
        image: uj5ghare/techdome-frontend:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env:
          - name: NEXT_PUBLIC_API_BASE_URL
            value: "http://127.0.0.1:8000/api"